using System.Linq;
using NUnit.Framework;

namespace RemoveUnused
{
    internal class XmlEnumeration
    {
        [Test]
        public void CanParseXmlFile()
        {
            var xml = @"<?xml version='1.0' encoding='utf-8'?>
<!-- Generated by JetBrains ReSharper 2020.2.4 -->
<Report ToolsVersion='202.0.20200925.65451'>
  <Issues>
    <Project Name='SQLCompareEngine'>
      <Issue TypeId='UnusedMember.Local' File='Engine\SQLCompareEngine\Engine\Comparison\Difference.cs' Offset='8859-8877' Line='259' Message=""Enum member 'MustRebuildTo1Mask' is never used"" />
    </Project>
  </Issues>
</Report>";
            var issue = Issue.ParseReSharperReportText(xml, @"E:\Work\SQLCompareEngine\").Single();
            Assert.NotNull(issue);
            Assert.AreEqual("UnusedMember.Local", issue.TypeId);
            Assert.AreEqual(@"E:\Work\SQLCompareEngine\Engine\SQLCompareEngine\Engine\Comparison\Difference.cs", issue.File);
            Assert.AreEqual(8859, issue.Start);
            Assert.AreEqual(8877, issue.End);
            Assert.AreEqual(259, issue.Line);
            Assert.AreEqual("Enum member 'MustRebuildTo1Mask' is never used", issue.Message);
        }
    }
}
